# Generated by Django 5.1.6 on 2025-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sport",
            field=models.TextField(blank=True, null=True),
        ),
    ]
