# Generated by Django 5.1.6 on 2025-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_sport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sport",
            field=models.BooleanField(default=False),
        ),
    ]
